### ISSUE TITLE
Requires `parking_lot` to be manually imported

### ISSUE THREAD

**Issue by askonomm** [fredmorcos/throttle_my_fn#1]
Great library! One thing I noticed when implementing this to my project was that the documentation says to just import the `throttle_my_fn::throttle;` but actually need to also import add `parking_lot` to dependencies and import it because this library itself is not doing that.

**Comment by fredmorcos** [comment]
Thank you for the report!

[I updated the documentation](https://github.com/fredmorcos/throttle_my_fn/blob/c00cd68f7d5ea2689fec3b00a9ee241e5b7f541e/README.md?plain=1#L18-L31) to mention that `parking_lot` needs to be added to the dependencies section of the `Cargo.toml` file.

However, I am not sure what you mean by

> and import it because this library itself is not doing that

Could you tell me what you needed to do to get this crate to work for you?

Thank you!

**Comment by askonomm** [comment]
I meant that I needed to 

1. Add `parking_lot` to Cargo.toml (you already updated the documentation about this so all good)
2. Add `use parking_lot;` to my own program (currently your documentation doesn't reflect this)

**Comment by fredmorcos** [comment]
Can you try getting your program to build without `use parking_lot`? I wrote a test program and it works without it. [The macro imports `parking_lot::{Mutex, const_mutex}`](https://github.com/fredmorcos/throttle_my_fn/blob/c00cd68f7d5ea2689fec3b00a9ee241e5b7f541e/src/lib.rs#L211).

**Comment by fredmorcos** [comment]
Do you consider this now fixed? Is it OK for you that I mark this issue as fixed?

**Comment by fredmorcos** [comment]
Fixed by https://github.com/fredmorcos/throttle_my_fn/commit/c00cd68f7d5ea2689fec3b00a9ee241e5b7f541e
